CREATE TABLE IF NOT EXISTS `cus_std_work_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_system` varchar(50) NOT NULL DEFAULT 'property' COMMENT '来源系统',
  `source_order_id` int NOT NULL COMMENT '来源工单ID，对应CustomerService.Id',
  `order_no` varchar(255) DEFAULT NULL COMMENT '工单编号',
  `project_id` int DEFAULT NULL COMMENT '项目/管理区ID，对应RegionId',
  `project_name` varchar(255) DEFAULT NULL COMMENT '项目名称，第一阶段可为空，后续关联组织表补充',
  `location_id` int DEFAULT NULL COMMENT '报事位置ID，对应OrganizationItemId',
  `location_name` varchar(255) DEFAULT NULL COMMENT '报事位置/楼栋/房间，第一阶段可由Place、Address或后续关联表补充',
  `location_text` varchar(500) DEFAULT NULL COMMENT '报事位置文本，兜底字段',
  `customer_id` int DEFAULT NULL COMMENT '客户ID',
  `report_person` varchar(255) DEFAULT NULL COMMENT '报事人/客户名称',
  `phone` varchar(255) DEFAULT NULL COMMENT '联系电话',
  `service_source` int DEFAULT NULL COMMENT '报事来源编码',
  `service_source_name` varchar(100) DEFAULT NULL COMMENT '报事来源名称，如自检自查、客户报修等',
  `service_type` int DEFAULT NULL COMMENT '服务类型编码',
  `service_type_name` varchar(100) DEFAULT NULL COMMENT '服务类型名称，如报修、投诉、建议等',
  `repair_status` int DEFAULT NULL COMMENT '报修状态编码',
  `repair_status_name` varchar(100) DEFAULT NULL COMMENT '报修状态名称，如已分配、已处理、已关闭',
  `dispatch_type_id` int DEFAULT NULL COMMENT '工单小类ID',
  `dispatch_type_name` varchar(255) DEFAULT NULL COMMENT '工单小类名称，后续关联DispatchTypes补充',
  `dispatch_type_parent_id` int DEFAULT NULL COMMENT '工单大类ID',
  `dispatch_type_parent_name` varchar(255) DEFAULT NULL COMMENT '工单大类名称，后续关联DispatchTypes补充',
  `dispatch_priority_id` int DEFAULT NULL COMMENT '工单优先级/时限ID',
  `dispatch_priority_name` varchar(100) DEFAULT NULL COMMENT '工单时限名称，如一天内处理、4小时内处理',
  `report_time` datetime DEFAULT NULL COMMENT '报事时间，优先取AcceptedDate',
  `accepted_time` datetime DEFAULT NULL COMMENT '录单/受理时间',
  `appointment_time` datetime DEFAULT NULL COMMENT '预约时间',
  `required_finish_time` datetime DEFAULT NULL COMMENT '要求完成时间',
  `dispatch_time` datetime DEFAULT NULL COMMENT '派工时间',
  `start_process_time` datetime DEFAULT NULL COMMENT '开始处理时间',
  `finish_time` datetime DEFAULT NULL COMMENT '派工完成时间',
  `confirm_time` datetime DEFAULT NULL COMMENT '确认/关闭时间',
  `report_content` varchar(1500) DEFAULT NULL COMMENT '报事详情',
  `content_keyword` varchar(100) DEFAULT NULL COMMENT '报事关键词，用于模型分组',
  `content_normalized` varchar(500) DEFAULT NULL COMMENT '标准化后的报事内容',
  `comment_level` int DEFAULT NULL COMMENT '评价等级编码',
  `comment_level_name` varchar(100) DEFAULT NULL COMMENT '评价等级名称，如好评、中评、差评',
  `comment_content` varchar(500) DEFAULT NULL COMMENT '评价内容',
  `comment_date` datetime DEFAULT NULL COMMENT '评价时间',
  `comment_by_customer` tinyint(1) DEFAULT 0 COMMENT '是否客户评价',
  `has_history` tinyint(1) DEFAULT 0 COMMENT '是否存在处理记录',
  `history_count` int DEFAULT 0 COMMENT '处理记录数量',
  `last_history_time` datetime DEFAULT NULL COMMENT '最后一次处理记录时间',
  `last_history_content` varchar(1000) DEFAULT NULL COMMENT '最后一次处理记录内容',
  `last_word_content` text COMMENT '最后一次人工处理说明/回单内容',
  `is_repair_order` tinyint(1) DEFAULT 0 COMMENT '是否报修类工单',
  `is_closed` tinyint(1) DEFAULT 0 COMMENT '是否已关闭',
  `is_finished` tinyint(1) DEFAULT 0 COMMENT '是否已处理/已完成',
  `is_valid` tinyint(1) DEFAULT 1 COMMENT '是否有效数据',
  `raw_sync_time` datetime DEFAULT NULL COMMENT '原始表同步时间',
  `std_build_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准表生成时间',
  `std_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准表更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_order` (`source_system`, `source_order_id`),
  KEY `idx_order_no` (`order_no`), KEY `idx_project_id` (`project_id`), KEY `idx_location_id` (`location_id`),
  KEY `idx_location_name` (`location_name`), KEY `idx_report_time` (`report_time`), KEY `idx_service_type` (`service_type`),
  KEY `idx_repair_status` (`repair_status`), KEY `idx_dispatch_type_id` (`dispatch_type_id`), KEY `idx_content_keyword` (`content_keyword`),
  KEY `idx_model_group` (`project_id`, `location_name`, `dispatch_type_name`, `content_keyword`, `report_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智慧纪检标准工单主表';

CREATE TABLE IF NOT EXISTS `cus_std_work_order_history` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_system` varchar(50) NOT NULL DEFAULT 'property' COMMENT '来源系统',
  `source_history_id` int NOT NULL COMMENT '来源处理记录ID，对应CustomerServiceHistory.Id',
  `source_order_id` int NOT NULL COMMENT '来源工单ID，对应CustomerService.Id',
  `order_no` varchar(255) DEFAULT NULL COMMENT '工单编号，冗余方便查询',
  `operation_time` datetime NOT NULL COMMENT '操作时间',
  `operation_user_id` varchar(450) DEFAULT NULL COMMENT '操作人ID',
  `operation_user_name` varchar(255) DEFAULT NULL COMMENT '操作人姓名，后续关联用户表补充',
  `operation_status` int DEFAULT NULL COMMENT '操作类型/流转状态编码',
  `operation_status_name` varchar(100) DEFAULT NULL COMMENT '操作类型名称，后续可通过字典转换',
  `operation_content` varchar(1000) DEFAULT NULL COMMENT '操作内容',
  `word_content` longtext COMMENT '人工处理说明/回单内容',
  `dispatch_id` int DEFAULT NULL COMMENT '派工单ID',
  `complaint_handle_id` int DEFAULT NULL COMMENT '投诉处理ID',
  `is_dispatch` tinyint(1) DEFAULT 0 COMMENT '是否派工记录',
  `is_start_process` tinyint(1) DEFAULT 0 COMMENT '是否开始处理记录',
  `is_finish` tinyint(1) DEFAULT 0 COMMENT '是否完成/回单记录',
  `is_confirm` tinyint(1) DEFAULT 0 COMMENT '是否确认记录',
  `is_return_visit` tinyint(1) DEFAULT 0 COMMENT '是否回访记录',
  `is_close` tinyint(1) DEFAULT 0 COMMENT '是否关闭记录',
  `is_valid` tinyint(1) DEFAULT 1 COMMENT '是否有效数据',
  `raw_sync_time` datetime DEFAULT NULL COMMENT '原始表同步时间',
  `std_build_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准表生成时间',
  `std_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准表更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_history` (`source_system`, `source_history_id`),
  KEY `idx_source_order_id` (`source_order_id`), KEY `idx_order_no` (`order_no`), KEY `idx_operation_time` (`operation_time`),
  KEY `idx_operation_status` (`operation_status`), KEY `idx_dispatch_id` (`dispatch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智慧纪检标准工单处理记录表';

CREATE TABLE IF NOT EXISTS `cus_keyword_rule_config` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `rule_type` varchar(50) NOT NULL COMMENT '规则类型，如WORK_ORDER_KEYWORD',
  `keyword` varchar(100) NOT NULL COMMENT '关键词',
  `standard_keyword` varchar(100) NOT NULL COMMENT '标准关键词',
  `priority` int DEFAULT 100 COMMENT '优先级，数字越小越优先',
  `enabled` tinyint(1) DEFAULT 1 COMMENT '是否启用',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`), UNIQUE KEY `uk_rule_keyword` (`rule_type`,`keyword`), KEY `idx_rule_type_enabled` (`rule_type`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智慧纪检关键词规则配置表';

INSERT INTO cus_keyword_rule_config(rule_type, keyword, standard_keyword, priority, enabled) VALUES
('WORK_ORDER_KEYWORD', '漏水', '漏水', 10, 1),('WORK_ORDER_KEYWORD', '堵', '堵塞', 20, 1),('WORK_ORDER_KEYWORD', '跳闸', '跳闸', 30, 1),
('WORK_ORDER_KEYWORD', '照明', '照明', 40, 1),('WORK_ORDER_KEYWORD', '灯', '照明', 41, 1),('WORK_ORDER_KEYWORD', '玻璃', '玻璃', 50, 1),
('WORK_ORDER_KEYWORD', '消防', '消防', 60, 1),('WORK_ORDER_KEYWORD', '门禁', '门禁', 70, 1),('WORK_ORDER_KEYWORD', '电梯', '电梯', 80, 1),
('WORK_ORDER_KEYWORD', '空调', '空调', 90, 1),('WORK_ORDER_KEYWORD', '清理', '清理', 100, 1),('WORK_ORDER_KEYWORD', '卫生', '清理', 101, 1),
('WORK_ORDER_KEYWORD', '违停', '违停', 110, 1),('WORK_ORDER_KEYWORD', '乱停', '违停', 111, 1),('WORK_ORDER_KEYWORD', '电动车', '电动车', 120, 1),
('WORK_ORDER_KEYWORD', '电瓶车', '电动车', 121, 1),('WORK_ORDER_KEYWORD', '小车', '车辆', 130, 1),('WORK_ORDER_KEYWORD', '机动车', '车辆', 131, 1),
('WORK_ORDER_KEYWORD', '花盆', '花盆', 140, 1),('WORK_ORDER_KEYWORD', '树枝', '树枝', 150, 1),('WORK_ORDER_KEYWORD', '枯树', '树枝', 151, 1)
ON DUPLICATE KEY UPDATE standard_keyword=VALUES(standard_keyword),priority=VALUES(priority),enabled=VALUES(enabled);
CREATE TABLE IF NOT EXISTS `cus_std_arrear_bill` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_system` varchar(50) NOT NULL DEFAULT 'property' COMMENT '来源系统',
  `source_detail_id` bigint NOT NULL COMMENT '来源明细ID',
  `project_id` bigint DEFAULT NULL COMMENT '项目ID',
  `project_name` varchar(255) DEFAULT NULL COMMENT '项目名称',
  `customer_id` bigint DEFAULT NULL COMMENT '客户ID',
  `customer_name` varchar(255) DEFAULT NULL COMMENT '客户名称',
  `room_id` bigint DEFAULT NULL COMMENT '房间ID',
  `room_name` varchar(255) DEFAULT NULL COMMENT '房间名称',
  `bill_no` varchar(128) DEFAULT NULL COMMENT '账单号',
  `fee_item_name` varchar(255) DEFAULT NULL COMMENT '费用项',
  `bill_date` date DEFAULT NULL COMMENT '应收日期',
  `due_date` date DEFAULT NULL COMMENT '应缴日期',
  `arrear_principal` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '欠费本金',
  `raw_sync_time` datetime DEFAULT NULL COMMENT '原始表同步时间',
  `std_build_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准表生成时间',
  `std_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准表更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_detail` (`source_system`, `source_detail_id`),
  KEY `idx_arrear_group` (`project_id`, `customer_id`, `room_id`),
  KEY `idx_due_date` (`due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='欠费账单标准表';

CREATE TABLE IF NOT EXISTS `cus_std_fee_reduction` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_system` varchar(50) NOT NULL DEFAULT 'property' COMMENT '来源系统',
  `source_detail_id` bigint NOT NULL COMMENT '来源明细ID',
  `stat_year` int NOT NULL COMMENT '统计年度',
  `project_id` bigint DEFAULT NULL COMMENT '项目ID',
  `project_name` varchar(255) DEFAULT NULL COMMENT '项目名称',
  `room_id` bigint DEFAULT NULL COMMENT '房间ID',
  `room_name` varchar(255) DEFAULT NULL COMMENT '房间名称',
  `fee_item_name` varchar(255) DEFAULT NULL COMMENT '费用项',
  `reduction_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '减免金额',
  `raw_sync_time` datetime DEFAULT NULL COMMENT '原始表同步时间',
  `std_build_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '标准表生成时间',
  `std_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '标准表更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_detail` (`source_system`, `source_detail_id`),
  KEY `idx_reduction_group` (`stat_year`, `project_id`, `room_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='费用减免标准表';
