CREATE TABLE IF NOT EXISTS `cus_model_repeat_repair_result` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `model_batch_no` varchar(64) NOT NULL COMMENT '模型批次号',
  `project_id` int DEFAULT NULL COMMENT '项目ID',
  `project_name` varchar(255) DEFAULT NULL COMMENT '项目名称',
  `location_key` varchar(255) NOT NULL COMMENT '位置分组Key',
  `location_name` varchar(255) DEFAULT NULL COMMENT '位置名称',
  `dispatch_type_name` varchar(255) DEFAULT NULL COMMENT '工单小类',
  `dispatch_type_parent_name` varchar(255) DEFAULT NULL COMMENT '工单大类',
  `content_keyword` varchar(100) DEFAULT NULL COMMENT '问题关键词',
  `stat_start_time` datetime NOT NULL COMMENT '统计开始时间',
  `stat_end_time` datetime NOT NULL COMMENT '统计结束时间',
  `repeat_count` int NOT NULL COMMENT '重复次数',
  `warning_level` varchar(20) NOT NULL COMMENT '预警等级：一级/二级/三级',
  `warning_title` varchar(255) DEFAULT NULL COMMENT '预警标题',
  `warning_content` text COMMENT '预警内容',
  `related_order_ids` text COMMENT '关联工单ID列表',
  `related_order_nos` text COMMENT '关联工单编号列表',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_model_batch_no` (`model_batch_no`),
  KEY `idx_project_location` (`project_id`, `location_key`),
  KEY `idx_warning_level` (`warning_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='重复维修与过度维修模型结果表';
