-- 目标表DDL（MySQL 8 / utf8mb4）
-- 创建 5 张 SQL Server 原始同步表及执行日志表
CREATE TABLE IF NOT EXISTS cus_raw_customer_service (
  source_id int NOT NULL,
  voucher_no varchar(255) DEFAULT NULL,
  region_id int DEFAULT NULL,
  service_source int NOT NULL,
  customer_name varchar(255) DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  finish_time_required datetime DEFAULT NULL,
  accepted_date datetime DEFAULT NULL,
  details varchar(1500) DEFAULT NULL,
  service_type int NOT NULL,
  comment int DEFAULT NULL,
  comment_content varchar(500) DEFAULT NULL,
  complaint_status int DEFAULT NULL,
  confirm_time datetime DEFAULT NULL,
  sync_batch_no varchar(64) DEFAULT NULL,
  sync_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (source_id), KEY idx_ics_accepted_date (accepted_date), KEY idx_ics_region_id (region_id), KEY idx_ics_voucher_no (voucher_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cus_raw_customer_service_history (
  source_id int NOT NULL,
  created_by_id varchar(450) DEFAULT NULL,
  create_date datetime NOT NULL,
  content varchar(255) NOT NULL,
  customer_service_id int NOT NULL,
  operation_status int NOT NULL DEFAULT 0,
  complaint_handle_id int DEFAULT NULL,
  dispatch_id int DEFAULT NULL,
  word_content longtext,
  sync_batch_no varchar(64) DEFAULT NULL,
  sync_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (source_id), KEY idx_icsh_customer_service_id (customer_service_id), KEY idx_icsh_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `cus_raw_organization_item` (
  `source_id` int NOT NULL COMMENT 'SQL Server OrganizationItem.Id',
  `parent_id` int DEFAULT NULL COMMENT '父级ID',
  `name` varchar(255) DEFAULT NULL COMMENT '名称，对应OrganizationItem.Name',
  `code` varchar(255) DEFAULT NULL COMMENT '编码',
  `item_type` int NOT NULL COMMENT '组织项类型',
  `address` varchar(255) DEFAULT NULL COMMENT '地址',
  `tel` varchar(255) DEFAULT NULL COMMENT '电话',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `region_id` int DEFAULT NULL COMMENT '所属区域ID，对应OrganizationItem.RegionId',
  `building_id` int DEFAULT NULL COMMENT '楼栋ID',
  `company_id` int DEFAULT NULL COMMENT '公司ID',
  `group_id` int DEFAULT NULL COMMENT '组团ID',
  `unit_id` int DEFAULT NULL COMMENT '单元ID',
  `city_id` int DEFAULT NULL COMMENT '城市ID',
  `building_type` int DEFAULT NULL COMMENT '楼栋类型',
  `floors` int DEFAULT NULL COMMENT '楼层数',
  `floor` int DEFAULT NULL COMMENT '楼层',
  `purpose` int DEFAULT NULL COMMENT '用途',
  `house_status` int DEFAULT NULL COMMENT '房屋状态',
  `house_state` int DEFAULT NULL COMMENT '房屋状态2',
  `house_type_id` int DEFAULT NULL COMMENT '房屋类型ID',
  `discriminator` varchar(255) NOT NULL COMMENT '实体类型标识',
  `hierarchical_path` text COMMENT '层级路径',
  `contact` text COMMENT '联系人',
  `contact_phone` text COMMENT '联系电话',
  `phone` text COMMENT '电话',
  `email` text COMMENT '邮箱',
  `is_virtual` tinyint(1) DEFAULT 0 COMMENT '是否虚拟',
  `is_disabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否禁用',
  `is_rentable` tinyint(1) DEFAULT NULL COMMENT '是否可租',
  `is_rented` tinyint(1) DEFAULT NULL COMMENT '是否已租',
  `is_sold` tinyint(1) DEFAULT NULL COMMENT '是否已售',
  `is_lease_out` tinyint(1) DEFAULT NULL COMMENT '是否租出',
  `uuid` text COMMENT 'UUID',
  `number` text COMMENT '编号',
  `terminal_code` text COMMENT '终端编码',
  `brand_code` text COMMENT '品牌编码',
  `check_in_date` datetime DEFAULT NULL COMMENT '入住日期',
  `handover_date` datetime DEFAULT NULL COMMENT '交付日期',
  `sold_time` datetime DEFAULT NULL COMMENT '出售时间',
  `update_time` datetime DEFAULT NULL COMMENT '源系统更新时间',
  `sync_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '同步时间',
  PRIMARY KEY (`source_id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_region_id` (`region_id`),
  KEY `idx_building_id` (`building_id`),
  KEY `idx_company_id` (`company_id`),
  KEY `idx_group_id` (`group_id`),
  KEY `idx_unit_id` (`unit_id`),
  KEY `idx_item_type` (`item_type`),
  KEY `idx_name` (`name`),
  KEY `idx_is_disabled` (`is_disabled`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='物业系统组织项目位置原始同步表';

CREATE TABLE IF NOT EXISTS cus_sync_task_log (
  id bigint NOT NULL AUTO_INCREMENT,
  task_code varchar(100) NOT NULL,
  sync_batch_no varchar(64) NOT NULL,
  sync_type varchar(20) NOT NULL,
  start_time datetime NOT NULL,
  end_time datetime DEFAULT NULL,
  status varchar(20) NOT NULL,
  read_count int DEFAULT 0,
  write_count int DEFAULT 0,
  error_message text,
  PRIMARY KEY (id), KEY idx_task_code_time (task_code,start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `cus_raw_materials_inventory_request` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_id` int NOT NULL COMMENT 'SQL Server MaterialsInventoryRequest.Id，源表主键',
  `supplier_id` int DEFAULT NULL COMMENT '供应商ID，关联Supplier表',
  `request_type` varchar(255) DEFAULT NULL COMMENT '申请类型/单据类型，例如内部领用、采购入库、销售出库等',
  `bill_no` varchar(255) DEFAULT NULL COMMENT '单据号，内部领用场景下为内部领用单号',
  `shipment_number` varchar(255) DEFAULT NULL COMMENT '发货单号/出货单号',
  `total_count` decimal(19,5) DEFAULT NULL COMMENT '单据总数量',
  `request_date` datetime DEFAULT NULL COMMENT '申请时间/制单时间',
  `request_user_id` int DEFAULT NULL COMMENT '申请人ID',
  `related_customer_id` int DEFAULT NULL COMMENT '关联客户ID',
  `status` int NOT NULL COMMENT '单据状态，例如0待审核、2已完成，具体以业务系统字典为准',
  `confirm_date` datetime DEFAULT NULL COMMENT '审核/确认时间',
  `confirm_user_id` int DEFAULT NULL COMMENT '审核人/确认人ID',
  `payment_date` datetime DEFAULT NULL COMMENT '付款时间',
  `related_user_id` int DEFAULT NULL COMMENT '关联人员ID，内部领用场景下通常表示领用人',
  `need_payment_money` decimal(19,5) DEFAULT NULL COMMENT '应付款金额',
  `remark` varchar(255) DEFAULT NULL COMMENT '单据备注',
  `organization_item_id` int NOT NULL COMMENT '项目ID，关联OrganizationItem.Id',
  `total_taxation` decimal(19,5) DEFAULT NULL COMMENT '总税额',
  `total_pre_tax_amount` decimal(19,5) DEFAULT NULL COMMENT '税前总金额',
  `discounted_price` decimal(19,5) DEFAULT NULL COMMENT '折扣金额/优惠后金额',
  `repair_bill_no` varchar(255) DEFAULT NULL COMMENT '关联维修工单号，用于关联维修工单',
  `is_upgrade_data` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否升级数据',
  `inventory_begn_date` date DEFAULT NULL COMMENT '盘点开始时间',
  `inventory_end_date` date DEFAULT NULL COMMENT '盘点结束时间',
  `raw_sync_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '同步入库时间',
  `raw_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '原始表更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_id` (`source_id`),
  KEY `idx_request_type` (`request_type`),
  KEY `idx_bill_no` (`bill_no`),
  KEY `idx_request_date` (`request_date`),
  KEY `idx_status` (`status`),
  KEY `idx_organization_item_id` (`organization_item_id`),
  KEY `idx_repair_bill_no` (`repair_bill_no`),
  KEY `idx_raw_sync_time` (`raw_sync_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='物料流转申请单原始表';

CREATE TABLE IF NOT EXISTS `cus_raw_materials_inventory_request_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_id` int NOT NULL COMMENT 'SQL Server MaterialsInventoryRequestDetail.Id，源表主键',
  `materials_inventory_request_id` int NOT NULL COMMENT '物料流转申请主表ID，对应SQL Server MaterialsInventoryRequest.Id',
  `material_id` int NOT NULL COMMENT '物资ID，关联Material表',
  `materials_inventory_id` int DEFAULT NULL COMMENT '库存记录ID，关联MaterialsInventory表',
  `source_warehouse_id` int DEFAULT NULL COMMENT '源仓库ID',
  `source_warehouse_area_id` int DEFAULT NULL COMMENT '源库区ID',
  `target_warehouse_id` int DEFAULT NULL COMMENT '目标仓库ID',
  `target_warehouse_area_id` int DEFAULT NULL COMMENT '目标库区ID',
  `request_count` decimal(19,5) DEFAULT NULL COMMENT '申请数量/领用数量，对应SQL Server字段[Count]',
  `actual_count` decimal(19,5) DEFAULT NULL COMMENT '实际数量',
  `buying_price` decimal(19,5) DEFAULT NULL COMMENT '采购价',
  `supplier_price` decimal(19,5) DEFAULT NULL COMMENT '供应商价格',
  `sale_price` decimal(19,5) DEFAULT NULL COMMENT '销售价',
  `transfer_price` decimal(19,5) DEFAULT NULL COMMENT '调拨价',
  `settlement_price` decimal(19,5) DEFAULT NULL COMMENT '结算价',
  `wholesale_price` decimal(19,5) DEFAULT NULL COMMENT '批发价',
  `taxation` decimal(19,5) DEFAULT NULL COMMENT '税额',
  `return_price` decimal(19,5) DEFAULT NULL COMMENT '退货价格',
  `remark` varchar(255) DEFAULT NULL COMMENT '明细备注/用途说明',
  `transfer_supplier_id` int DEFAULT NULL COMMENT '调拨供应商ID',
  `created_date` datetime DEFAULT NULL COMMENT '明细创建时间',
  `raw_sync_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '同步入库时间',
  `raw_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '原始表更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_source_id` (`source_id`),
  KEY `idx_request_id` (`materials_inventory_request_id`),
  KEY `idx_material_id` (`material_id`),
  KEY `idx_created_date` (`created_date`),
  KEY `idx_source_warehouse` (`source_warehouse_id`),
  KEY `idx_target_warehouse` (`target_warehouse_id`),
  KEY `idx_raw_sync_time` (`raw_sync_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='物料流转申请单明细原始表';
