package com.example.smartinspection.service;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

/**
 * 财务风险模型服务（大额欠费 + 费用减免）。
 * <p>
 * 本实现与当前“新视窗”收费明细字段口径保持一致：
 * - 欠费标准层使用 Preinct/Owner/House/Charge* / Arrears 等字段；
 * - 减免标准层使用 Discount/DelayDiscount/DiscountDate/CheckTime 等字段；
 * - 结果层扩展 bill_count / fee_item_names / related_detail_ids 等审计字段。
 * </p>
 */
@Service
public class CusChargeRiskModelService {
    private final JdbcTemplate mysqlJdbcTemplate;

    public CusChargeRiskModelService(@Qualifier("mysqlJdbcTemplate") JdbcTemplate mysqlJdbcTemplate) {
        this.mysqlJdbcTemplate = mysqlJdbcTemplate;
    }

    /** 构建欠费/减免标准表（幂等）。 */
    public void buildArrearAndReductionStdTables() {
        mysqlJdbcTemplate.update(SqlHolder.BUILD_STD_ARREAR_BILL);
        mysqlJdbcTemplate.update(SqlHolder.BUILD_STD_FEE_REDUCTION);
    }

    /** 计算模型结果并汇总预警工单。 */
    public void calculateChargeRiskModels() {
        String batchNo = mysqlJdbcTemplate.queryForObject("SELECT DATE_FORMAT(NOW(), '%Y%m%d%H%i%s')", String.class);

        mysqlJdbcTemplate.execute("SET SESSION group_concat_max_len = 102400");

        mysqlJdbcTemplate.update(SqlHolder.CALC_LARGE_ARREAR_RESULT, batchNo);
        mysqlJdbcTemplate.update(SqlHolder.CALC_FEE_REDUCTION_RESULT, batchNo);

        mysqlJdbcTemplate.update("DELETE FROM cus_warning_order WHERE model_batch_no = ?", batchNo);
        mysqlJdbcTemplate.update(SqlHolder.INSERT_WARNING_ORDER_FROM_ARREAR, batchNo, batchNo);
        mysqlJdbcTemplate.update(SqlHolder.INSERT_WARNING_ORDER_FROM_REDUCTION, batchNo, batchNo);
    }

    private static class SqlHolder {
        private static final String BUILD_STD_ARREAR_BILL = "INSERT INTO cus_std_arrear_bill (" +
            "source_system,source_detail_id,project_id,project_name,customer_id,customer_name,customer_type,room_id,room_name,group_id,group_name,building_id,building_name,bill_no,fee_item_id,fee_item_name,charge_name,financial_item_name,bill_date,due_date,calc_start_date,calc_end_date,charge_amount,actual_charge_amount,paid_amount,arrear_principal,late_fee,pay_status,is_paid,paid_date,is_delete,is_red_ink,is_freezed,is_bad_debt,charge_bad_status,charge_bad_amount,charge_dull_status,charge_dull_amount,contract_id,contract_code,contract_name,account_book,actual_account_book,arrearage_reason,is_model_valid,invalid_reason,raw_create_time,raw_update_time,raw_sync_time,std_build_time,std_update_time) " +
            "SELECT 'new_window',r.Id,r.PreinctId,r.PreinctName,r.OwnerId,r.OwnerName,r.ownerType,r.HouseId,r.HouseName,r.groupId,r.groupName,r.buildingId,r.buildingName,r.fromSysAccountCode,r.ChargeItemId,r.ChargeItemName,r.ChargeName,r.belongFinancialItemName,r.ShouldChargeDate,r.ShouldChargeDate,r.CalcStartDate,r.CalcEndDate,CAST(IFNULL(r.ChargeSum,0) AS DECIMAL(18,2)),CAST(IFNULL(r.ActualChargeSum,0) AS DECIMAL(18,2)),CAST(IFNULL(r.PaidChargeSum,0) AS DECIMAL(18,2)),CAST(IFNULL(r.Arrears,0) AS DECIMAL(18,2)),CAST(IFNULL(r.late_fee,0) AS DECIMAL(18,2)),r.PayStatus,IFNULL(r.IsPaid,0),r.PaidDate,IFNULL(r.IsDelete,'0'),IFNULL(r.isRedInk,'0'),IFNULL(r.IsFreezed,0),IFNULL(r.IsBadDebt,0),IFNULL(r.chargeBadStatus,0),CAST(IFNULL(r.chargeBadAmount,0) AS DECIMAL(18,2)),IFNULL(r.chargeDullStatus,0),CAST(IFNULL(r.chargeDullAmount,0) AS DECIMAL(18,2)),r.ContractId,r.contractCode,r.ContractName,r.AccountBook,r.ActualAccountBook,r.arrearage_reason," +
            "CASE WHEN IFNULL(r.IsDelete,'0')<>'0' OR IFNULL(r.isRedInk,'0')<>'0' OR IFNULL(r.Arrears,0)<=0 OR r.ShouldChargeDate IS NULL OR r.ShouldChargeDate>CURDATE() OR IFNULL(r.IsBadDebt,0)=1 OR IFNULL(r.chargeBadStatus,0) IN (1,2) OR IFNULL(r.chargeDullStatus,0) IN (1,2) THEN 0 ELSE 1 END," +
            "CASE WHEN IFNULL(r.IsDelete,'0')<>'0' THEN '已删除' WHEN IFNULL(r.isRedInk,'0')<>'0' THEN '红冲账单' WHEN IFNULL(r.Arrears,0)<=0 THEN '无欠费金额' WHEN r.ShouldChargeDate IS NULL THEN '应收日期为空' WHEN r.ShouldChargeDate>CURDATE() THEN '未到应收日期' WHEN IFNULL(r.IsBadDebt,0)=1 THEN '已坏账' WHEN IFNULL(r.chargeBadStatus,0) IN (1,2) THEN '坏账/部分坏账' WHEN IFNULL(r.chargeDullStatus,0) IN (1,2) THEN '呆账/部分呆账' ELSE NULL END," +
            "r.CreateTime,r.UpdateTime,r.SysTime,NOW(),NOW() FROM cus_raw_charge_customerchargedetail r " +
            "ON DUPLICATE KEY UPDATE project_id=VALUES(project_id),project_name=VALUES(project_name),customer_id=VALUES(customer_id),customer_name=VALUES(customer_name),customer_type=VALUES(customer_type),room_id=VALUES(room_id),room_name=VALUES(room_name),group_id=VALUES(group_id),group_name=VALUES(group_name),building_id=VALUES(building_id),building_name=VALUES(building_name),bill_no=VALUES(bill_no),fee_item_id=VALUES(fee_item_id),fee_item_name=VALUES(fee_item_name),charge_name=VALUES(charge_name),financial_item_name=VALUES(financial_item_name),bill_date=VALUES(bill_date),due_date=VALUES(due_date),calc_start_date=VALUES(calc_start_date),calc_end_date=VALUES(calc_end_date),charge_amount=VALUES(charge_amount),actual_charge_amount=VALUES(actual_charge_amount),paid_amount=VALUES(paid_amount),arrear_principal=VALUES(arrear_principal),late_fee=VALUES(late_fee),pay_status=VALUES(pay_status),is_paid=VALUES(is_paid),paid_date=VALUES(paid_date),is_delete=VALUES(is_delete),is_red_ink=VALUES(is_red_ink),is_freezed=VALUES(is_freezed),is_bad_debt=VALUES(is_bad_debt),charge_bad_status=VALUES(charge_bad_status),charge_bad_amount=VALUES(charge_bad_amount),charge_dull_status=VALUES(charge_dull_status),charge_dull_amount=VALUES(charge_dull_amount),contract_id=VALUES(contract_id),contract_code=VALUES(contract_code),contract_name=VALUES(contract_name),account_book=VALUES(account_book),actual_account_book=VALUES(actual_account_book),arrearage_reason=VALUES(arrearage_reason),is_model_valid=VALUES(is_model_valid),invalid_reason=VALUES(invalid_reason),raw_create_time=VALUES(raw_create_time),raw_update_time=VALUES(raw_update_time),raw_sync_time=VALUES(raw_sync_time),std_update_time=NOW()";

        private static final String BUILD_STD_FEE_REDUCTION = "INSERT INTO cus_std_fee_reduction (source_system,source_detail_id,stat_year,project_id,project_name,customer_id,customer_name,customer_type,room_id,room_name,group_id,group_name,building_id,building_name,fee_item_id,fee_item_name,charge_name,financial_item_name,bill_date,due_date,calc_start_date,calc_end_date,charge_amount,actual_charge_amount,paid_amount,principal_reduction_amount,delay_reduction_amount,reduction_amount,discount_type,discount_reason,discount_user_id,discount_user_name,discount_date,delay_sum,delay_days,check_status,check_time,not_check_reason,discount_lock,discount_lock_amount,pay_status,is_paid,is_delete,is_red_ink,is_freezed,contract_id,contract_code,contract_name,account_book,actual_account_book,is_model_valid,invalid_reason,raw_create_time,raw_update_time,raw_sync_time,std_build_time,std_update_time) " +
            "SELECT 'new_window',r.Id,YEAR(COALESCE(r.DiscountDate,r.checkTime,r.UpdateTime,r.CreateTime)),r.PreinctId,r.PreinctName,r.OwnerId,r.OwnerName,r.ownerType,r.HouseId,r.HouseName,r.groupId,r.groupName,r.buildingId,r.buildingName,r.ChargeItemId,r.ChargeItemName,r.ChargeName,r.belongFinancialItemName,r.ShouldChargeDate,r.ShouldChargeDate,r.CalcStartDate,r.CalcEndDate,CAST(IFNULL(r.ChargeSum,0) AS DECIMAL(18,2)),CAST(IFNULL(r.ActualChargeSum,0) AS DECIMAL(18,2)),CAST(IFNULL(r.PaidChargeSum,0) AS DECIMAL(18,2)),CAST(IFNULL(r.Discount,0) AS DECIMAL(18,2)),CAST(IFNULL(r.DelayDiscount,0) AS DECIMAL(18,2)),CAST(IFNULL(r.Discount,0)+IFNULL(r.DelayDiscount,0) AS DECIMAL(18,2)),r.DiscountType,r.DiscountReason,r.DiscountUserId,r.DiscountUserName,r.DiscountDate,CAST(IFNULL(r.DelaySum,0) AS DECIMAL(18,2)),IFNULL(r.DelayDays,0),r.IsCheck,r.checkTime,r.NotCheckReason,IFNULL(r.discount_lock,0),CAST(IFNULL(r.discount_lock_amount,0) AS DECIMAL(18,2)),r.PayStatus,IFNULL(r.IsPaid,0),IFNULL(r.IsDelete,'0'),IFNULL(r.isRedInk,'0'),IFNULL(r.IsFreezed,0),r.ContractId,r.contractCode,r.ContractName,r.AccountBook,r.ActualAccountBook," +
            "CASE WHEN IFNULL(r.IsDelete,'0')<>'0' OR IFNULL(r.isRedInk,'0')<>'0' OR (IFNULL(r.Discount,0)<=0 AND IFNULL(r.DelayDiscount,0)<=0 AND IFNULL(r.discount_lock_amount,0)<=0) OR COALESCE(r.DiscountDate,r.checkTime,r.UpdateTime,r.CreateTime) IS NULL THEN 0 ELSE 1 END," +
            "CASE WHEN IFNULL(r.IsDelete,'0')<>'0' THEN '已删除' WHEN IFNULL(r.isRedInk,'0')<>'0' THEN '红冲账单' WHEN IFNULL(r.Discount,0)<=0 AND IFNULL(r.DelayDiscount,0)<=0 AND IFNULL(r.discount_lock_amount,0)<=0 THEN '无减免金额' WHEN COALESCE(r.DiscountDate,r.checkTime,r.UpdateTime,r.CreateTime) IS NULL THEN '减免日期为空' ELSE NULL END," +
            "r.CreateTime,r.UpdateTime,r.SysTime,NOW(),NOW() FROM cus_raw_charge_customerchargedetail r " +
            "ON DUPLICATE KEY UPDATE stat_year=VALUES(stat_year),project_id=VALUES(project_id),project_name=VALUES(project_name),customer_id=VALUES(customer_id),customer_name=VALUES(customer_name),customer_type=VALUES(customer_type),room_id=VALUES(room_id),room_name=VALUES(room_name),group_id=VALUES(group_id),group_name=VALUES(group_name),building_id=VALUES(building_id),building_name=VALUES(building_name),fee_item_id=VALUES(fee_item_id),fee_item_name=VALUES(fee_item_name),charge_name=VALUES(charge_name),financial_item_name=VALUES(financial_item_name),bill_date=VALUES(bill_date),due_date=VALUES(due_date),calc_start_date=VALUES(calc_start_date),calc_end_date=VALUES(calc_end_date),charge_amount=VALUES(charge_amount),actual_charge_amount=VALUES(actual_charge_amount),paid_amount=VALUES(paid_amount),principal_reduction_amount=VALUES(principal_reduction_amount),delay_reduction_amount=VALUES(delay_reduction_amount),reduction_amount=VALUES(reduction_amount),discount_type=VALUES(discount_type),discount_reason=VALUES(discount_reason),discount_user_id=VALUES(discount_user_id),discount_user_name=VALUES(discount_user_name),discount_date=VALUES(discount_date),delay_sum=VALUES(delay_sum),delay_days=VALUES(delay_days),check_status=VALUES(check_status),check_time=VALUES(check_time),not_check_reason=VALUES(not_check_reason),discount_lock=VALUES(discount_lock),discount_lock_amount=VALUES(discount_lock_amount),pay_status=VALUES(pay_status),is_paid=VALUES(is_paid),is_delete=VALUES(is_delete),is_red_ink=VALUES(is_red_ink),is_freezed=VALUES(is_freezed),contract_id=VALUES(contract_id),contract_code=VALUES(contract_code),contract_name=VALUES(contract_name),account_book=VALUES(account_book),actual_account_book=VALUES(actual_account_book),is_model_valid=VALUES(is_model_valid),invalid_reason=VALUES(invalid_reason),raw_create_time=VALUES(raw_create_time),raw_update_time=VALUES(raw_update_time),raw_sync_time=VALUES(raw_sync_time),std_update_time=NOW()";

        private static final String CALC_LARGE_ARREAR_RESULT = "INSERT INTO cus_model_large_arrear_result (model_batch_no,project_id,project_name,customer_id,customer_name,room_id,room_name,arrear_principal_total,earliest_due_date,arrear_age_days,amount_level,age_level,warning_level,bill_count,fee_item_names,related_detail_ids,warning_title,warning_content,create_time) " +
            "WITH base AS (SELECT project_id,project_name,customer_id,customer_name,room_id,room_name,SUM(IFNULL(arrear_principal,0)) arrear_principal_total,MIN(due_date) earliest_due_date,DATEDIFF(CURDATE(),MIN(due_date)) arrear_age_days,COUNT(*) bill_count,GROUP_CONCAT(DISTINCT fee_item_name ORDER BY fee_item_name SEPARATOR ',') fee_item_names,GROUP_CONCAT(source_detail_id ORDER BY due_date ASC SEPARATOR ',') related_detail_ids FROM cus_std_arrear_bill WHERE is_model_valid=1 AND IFNULL(arrear_principal,0)>0 AND due_date IS NOT NULL AND due_date<=CURDATE() GROUP BY project_id,project_name,customer_id,customer_name,room_id,room_name),level_calc AS (SELECT b.*,CASE WHEN b.arrear_principal_total>=100000 THEN 3 WHEN b.arrear_principal_total>=70000 THEN 2 WHEN b.arrear_principal_total>=50000 THEN 1 ELSE 0 END amount_level_num,CASE WHEN b.arrear_age_days>=730 THEN 3 WHEN b.arrear_age_days>=548 THEN 2 WHEN b.arrear_age_days>=365 THEN 1 ELSE 0 END age_level_num FROM base b),final_calc AS (SELECT l.*,GREATEST(l.amount_level_num,l.age_level_num) final_level_num,CASE l.amount_level_num WHEN 3 THEN '一级预警' WHEN 2 THEN '二级预警' WHEN 1 THEN '三级预警' ELSE NULL END amount_level,CASE l.age_level_num WHEN 3 THEN '一级预警' WHEN 2 THEN '二级预警' WHEN 1 THEN '三级预警' ELSE NULL END age_level,CASE GREATEST(l.amount_level_num,l.age_level_num) WHEN 3 THEN '一级预警' WHEN 2 THEN '二级预警' WHEN 1 THEN '三级预警' ELSE NULL END final_warning_level FROM level_calc l) SELECT CONCAT('LAR-',?),project_id,project_name,customer_id,customer_name,room_id,room_name,arrear_principal_total,earliest_due_date,arrear_age_days,amount_level,age_level,final_warning_level,bill_count,fee_item_names,related_detail_ids,'大额欠费财务风险预警',CONCAT('项目【',IFNULL(project_name,project_id),'】客户【',IFNULL(customer_name,customer_id),'】房间【',IFNULL(room_name,room_id),'】累计欠费本金 ',FORMAT(arrear_principal_total,2),' 元，涉及欠费账单 ',bill_count,' 笔，涉及费用项【',IFNULL(fee_item_names,'-'),'】，最早欠费日期 ',IFNULL(DATE_FORMAT(earliest_due_date,'%Y-%m-%d'),'-'),'，欠费账龄 ',IFNULL(arrear_age_days,0),' 天，金额等级【',IFNULL(amount_level,'未触发'),'】，账龄等级【',IFNULL(age_level,'未触发'),'】，最终触发【',final_warning_level,'】。'),NOW() FROM final_calc WHERE final_level_num>0";

        private static final String CALC_FEE_REDUCTION_RESULT = "INSERT INTO cus_model_fee_reduction_result (model_batch_no,stat_year,project_id,project_name,room_id,room_name,reduction_amount_total,project_year_rank,warning_level,bill_count,fee_item_names,discount_user_names,check_statuses,related_detail_ids,warning_title,warning_content,create_time) " +
            "WITH agg AS (SELECT stat_year,project_id,project_name,room_id,room_name,SUM(IFNULL(reduction_amount,0)) reduction_amount_total,COUNT(*) bill_count,GROUP_CONCAT(DISTINCT fee_item_name ORDER BY fee_item_name SEPARATOR ',') fee_item_names,GROUP_CONCAT(DISTINCT discount_user_name ORDER BY discount_user_name SEPARATOR ',') discount_user_names,GROUP_CONCAT(DISTINCT check_status ORDER BY check_status SEPARATOR ',') check_statuses,GROUP_CONCAT(source_detail_id ORDER BY discount_date ASC SEPARATOR ',') related_detail_ids FROM cus_std_fee_reduction WHERE is_model_valid=1 AND stat_year IS NOT NULL AND IFNULL(reduction_amount,0)>0 GROUP BY stat_year,project_id,project_name,room_id,room_name),ranked AS (SELECT a.*,ROW_NUMBER() OVER (PARTITION BY a.stat_year,a.project_id ORDER BY a.reduction_amount_total DESC,a.room_id ASC) project_year_rank FROM agg a),final_calc AS (SELECT r.*,CASE WHEN r.project_year_rank<=3 THEN '一级预警' WHEN r.project_year_rank<=5 THEN '二级预警' WHEN r.project_year_rank<=10 THEN '三级预警' ELSE NULL END warning_level FROM ranked r WHERE r.project_year_rank<=10) SELECT CONCAT('FR-',?),stat_year,project_id,project_name,room_id,room_name,reduction_amount_total,project_year_rank,warning_level,bill_count,fee_item_names,discount_user_names,check_statuses,related_detail_ids,'物业费用减免合规性探查预警',CONCAT('项目【',IFNULL(project_name,project_id),'】',stat_year,'年度房间【',IFNULL(room_name,room_id),'】累计减免金额 ',FORMAT(reduction_amount_total,2),' 元，涉及减免账单 ',bill_count,' 笔，涉及费用项【',IFNULL(fee_item_names,'-'),'】，减免操作人【',IFNULL(discount_user_names,'-'),'】，审核状态【',IFNULL(check_statuses,'-'),'】，项目内年度排名第 ',project_year_rank,'，触发【',warning_level,'】。'),NOW() FROM final_calc WHERE warning_level IS NOT NULL";

        private static final String INSERT_WARNING_ORDER_FROM_ARREAR = "INSERT INTO cus_warning_order (model_batch_no,warning_type,warning_level,project_id,project_name,biz_key,warning_title,warning_content) SELECT ?, 'LARGE_ARREAR',warning_level,project_id,project_name,CONCAT(IFNULL(customer_id,'NULL'),'#',IFNULL(room_id,'NULL')),warning_title,warning_content FROM cus_model_large_arrear_result WHERE model_batch_no=CONCAT('LAR-',?)";
        private static final String INSERT_WARNING_ORDER_FROM_REDUCTION = "INSERT INTO cus_warning_order (model_batch_no,warning_type,warning_level,project_id,project_name,biz_key,warning_title,warning_content) SELECT ?, 'FEE_REDUCTION',warning_level,project_id,project_name,CONCAT(stat_year,'#',IFNULL(room_id,'NULL')),warning_title,warning_content FROM cus_model_fee_reduction_result WHERE model_batch_no=CONCAT('FR-',?)";
    }
}
